spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cm
    username: postgres
    password: root
  jpa:
    show-sql: true

client-application:
  url: localhost
  port: 8080